baseURL = "https://gardener.cloud/"
title = "Gardener"
theme = "gardener"
metaDataFormat = "yaml"
languageCode = "en-US"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true
contentDir="content"
enableGitInfo = true
# Google Analytics Track ID
googleAnalytics = "UA-165447164-1"
disableHugoGeneratorInject = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    style = "vs"
    tabWidth = 4

[params]
  defaultURL = "https://github.com/kubernetes/documentation/tree/master/website/"
  editURL = "https://github.com/gardener/documentation/edit/master/website/"
  issueURL = "https://github.com/gardener/documentation/issues"
  copyright = "Copyright 2019-2021 Gardener project authors."
  privacyPolicyURL = "https://www.sap.com/corporate/en/legal/privacy.html"
  description = "Project Gardener Website - A Managed Kubernetes Service Done Right"
  # Google Tag Manager container
  googleTagsManager = "GTM-W2FGNSX"
  # Google Search Console site verification tag
  googleSiteVerificationTag = "9EoGiMwk2aq0E_tVh16iJgJbp7fbyqkfWH9b5sGybl0"
  [params.pageTopBar]
    display = true
    displayContributors = true
    displayLastUpdate = true
    displayEdit = true
    displayOriginURL = false

[outputs]
home = [ "HTML", "RSS" ]

